# Generated by Django 5.1.7 on 2025-05-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='description',
            field=models.CharField(default='No description available', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ledger.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
